framework: mocha
preRun:
     command:
        - export NPM_GLOBAL=$HOME/temp-module
        - mkdir NPM_GLOBAL
        - npm config --global set prefix NPM_GLOBAL
        - npm install typescript
        - echo "$DOT_CLASPRC" >> $HOME/.clasprc.json
        - npm run build
        - export SCRIPT_ID=1EwE84eZCSBPcaAiJzCnDjmxMVnLQrDyhSKq1oZY6q-3x4BIDHgQefCnL
        - export PROJECT_ID=project-id-3961473932623644264
        - npm run pretest
preMerge:
  pattern:
    - "./build/test/files.js"
postMerge:
  pattern:
    - "./build/test/files.js"
postRun:
     command:
        - node --version
configFile: "mocharc.yml"
version: 2.0

