framework: mocha
preRun:
     command:
        - npm install
        - npm run pretest
preMerge:
  pattern:
    - "./build/test/files.js"
postMerge:
  pattern:
    - "./build/test/files.js"
postRun:
     command:
        - node --version
configFile: "mocharc.yml"
version: 2.0
